version: "3.7"

networks:
  neo4j-lan:

services:

  neo4j-core1:
    image: neo4j:3.5-enterprise
    networks:
      - neo4j-lan
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/conf:/conf
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/data:/data
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/logs:/logs
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_memory_pagecache_size=1024M
      - NEO4J_dbms_memory_heap_max__size=1024M
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]

  neo4j-core2:
    image: neo4j:3.5-enterprise
    networks:
      - neo4j-lan
    ports:
      - 7475:7475
      - 6478:6478
      - 7688:7688
    volumes:
      - $HOME/markov-bot/neo4j-docker/neo4j-core2/conf:/conf
      - $HOME/markov-bot/neo4j-docker/neo4j-core2/data:/data
      - $HOME/markov-bot/neo4j-docker/neo4j-core2/logs:/logs
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_memory_pagecache_size=1024M
      - NEO4J_dbms_memory_heap_max__size=1024M
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]

  neo4j-core3:
    image: neo4j:3.5-enterprise
    networks:
      - neo4j-lan
    ports:
      - 7476:7476
      - 6479:6479
      - 7689:7689
    volumes:
      - $HOME/markov-bot/neo4j-docker/neo4j-core3/conf:/conf
      - $HOME/markov-bot/neo4j-docker/neo4j-core3/data:/data
      - $HOME/markov-bot/neo4j-docker/neo4j-core3/logs:/logs
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
      - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
      - NEO4J_causal__clustering_initial__discovery__members=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_https_listen__address=:6479
      - NEO4J_dbms_connector_bolt_listen__address=:7689
      - NEO4J_dbms_memory_pagecache_size=1024M
      - NEO4J_dbms_memory_heap_max__size=1024M
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]

  neo4j-read1:
    image: neo4j:3.5-enterprise
    networks:
      - neo4j-lan
    ports:
      - 7477:7477
      - 6480:6480
      - 7690:7690
    volumes:
      - $HOME/markov-bot/neo4j-docker/neo4j-read1/conf:/conf
      - $HOME/markov-bot/neo4j-docker/neo4j-read1/data:/data
      - $HOME/markov-bot/neo4j-docker/neo4j-read1/logs:/logs
      - $HOME/markov-bot/neo4j-docker/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_initialDiscoveryMembers=neo4j-core1:5000,neo4j-core2:5000,neo4j-core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7477
      - NEO4J_dbms_connector_https_listen__address=:6480
      - NEO4J_dbms_connector_bolt_listen__address=:7690
      - NEO4J_dbms_memory_pagecache_size=1024M
      - NEO4J_dbms_memory_heap_max__size=1024M
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]